apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: {{ .Values.securityfachade.service.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: {{ .Values.securityfachade.service.name }}
spec:
  tls:
  - hosts:
    {{ if eq .Values.gitlab.env "staging" }}
    - staging.security-facade.iotcrawler.eu
    {{ else }}
    - security-facade.iotcrawler.eu
    {{ end }}
    secretName: security-facade-{{ .Values.gitlab.env }}-tls22
  rules:
  {{ if eq .Values.gitlab.env "staging" }}
  - host: staging.security-facade.iotcrawler.eu
  {{ else }}
  - host: security-facade.iotcrawler.eu
  {{ end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.securityfachade.service.name }}
          servicePort: {{ .Values.securityfachade.service.internalPort }}