apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}  
  name: security-configmap
data:
  network_configuration.json: |
{{ .Files.Get "../configuration_files/config/network_configuration.json" | indent 4 }}