apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}  
  name: security-configmap
data:
  network_configuration.json: |
{{ .Files.Get "config/network_configuration.json" | indent 4 }}
  configuration.json: |
{{ .Files.Get "config/configuration.json" | indent 4 }}
  app_configuration.json: |
{{ .Files.Get "config/app_configuration.json" | indent 4 }}